### ISSUE TITLE
Use wp_add_inline_script()

### ISSUE THREAD

**Issue by GaryJones** [GaryJones/genesis-js-no-js#3]
See https://developer.wordpress.org/reference/functions/wp_add_inline_script/

**Comment by GaryJones** [comment]
This would also remove the `<script>` tag and it's `type` attribute.

**Comment by GaryJones** [comment]
With an inline string, it could also be delivered in a minified format.

**Comment by christophherr** [comment]
We were just talking about your plugin on Slack.
I could not get wp_add_inline_script to run early enough to prevent the desktop menu to show briefly on mobile. Also, there is not really a dependency to hook to.

Enqueuing as a file worked with a setTimeout workaround.
```
const genesisJsNoJs = ( () => {
	const changeClasses = () => {
		const c = document.body.classList;
		c.remove( 'no-js' );
		c.add( 'js' );
	};

	return {
		changeClasses
	};
})();

window.onload = setTimeout( genesisJsNoJs.changeClasses, 0 );
```
