### ISSUE TITLE
Regex may not always match the desired substring.

### ISSUE THREAD

**Issue by timothyjensen** [GaryJones/genesis-js-no-js#4]
The regex used in the `replace()` method may not always match the substring `'no-js'`: https://github.com/GaryJones/genesis-js-no-js/blob/7bc90e329016f33a8bca54e27c35850b8e4e8dbd/includes/class-genesis-js-no-js.php#L63

Say we have a body class of `'home alpha-plugin-no-js no-js'`, then the regex will match the first occurrence of `'no-js'` and result in a body class of `'home alpha-plugin-js no-js'`.  

To avoid this, we can add the global flag to the regex, but that might conflict with other plugins.  Another idea is to add a space so that the regex matches `/ no-js/` (with a preceding space).  We could also create a more complex regex, but that might not be necessary.

**Comment by GaryJones** [comment]
The space won't match when the classname is the first class in the attribute value (i.e. has a `"` before it).

But you're right, this regex could be improved.

**Comment by GaryJones** [comment]
@timothyjensen 

How about a regex of `([" ])no-js([" ])`, and a replace of `$1js$2`?

![screenshot 2017-08-23 02 52 41](https://user-images.githubusercontent.com/88371/29595236-2a5be07a-87ae-11e7-9e39-5dd52d72f1e9.png)

**Comment by timothyjensen** [comment]
@GaryJones I tested that out on a demo site and it didn't seem to work for me, possibly because quotation marks don't occur in the search string.

How about `(^|\s)(no-js)(?![^\s])` and replace with ` js` (with a leading space)?

**Comment by timothyjensen** [comment]
<img width="860" alt="screen shot 2017-08-23 at 7 14 48 am" src="https://user-images.githubusercontent.com/16006205/29613243-2d41a6e2-87d3-11e7-83a4-a5315e26211c.png">

**Comment by GaryJones** [comment]
Better yet, why don't we use `document.body.classList` to grab the classes as an array instead?

```js
var c = document.body.classList;
c = c.remove('no-js');
c = c.add('js');
document.body.classList = c;
```

**Comment by timothyjensen** [comment]
Brilliant!  That's much better than a complex regex.

**Comment by timothyjensen** [comment]
Could reduce a few bytes with:
```js
var c = document.body.classList;
c.remove('no-js');
c.add('js');
```

**Comment by GaryJones** [comment]
@timothyjensen Feel free to checkout and give 70c2126cee41e8a6d792dda223c38a33036233f1 a go (or the rest of the `develop` branch, if you're running PHP 7.1+).

**Comment by timothyjensen** [comment]
Great, I just tested `develop` on PHP 7.1.4 with no issues.

**Comment by GaryJones** [comment]
https://github.com/GaryJones/genesis-js-no-js/releases/tag/3.0.0 and https://github.com/GaryJones/genesis-js-no-js/releases/tag/3.0.1 have now been released which contains the improvement from here.
